apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-db
  labels:
    app: backup-db
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-db
            image: mongo
            command: ["mongodump","--host", "mongodb:27017","--out", "/dump", "--verbose"]
            volumeMounts:
            - mountPath: "/dump"
              name: mongodumps
          volumes:
          - name: mongodumps
            persistentVolumeClaim:
              claimName: mongodump-pv-claim
          restartPolicy: OnFailure
