apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restore-db
  labels:
    app: restore-db
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restore-db
            image: mongo
            command: ["mongorestore","--host", "mongodb:27017","--verbose","/dump"]
            volumeMounts:
            - mountPath: "/dump"
              name: mongodumps
          volumes:
          - name: mongodumps
            persistentVolumeClaim:
              claimName: mongodump-pv-claim
          restartPolicy: Never
