apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-service
    spec:
      containers:
      - image: order-service:0.1
        name: order
        ports:
        - containerPort: 8002
        resources: {}
        imagePullPolicy: Never
      restartPolicy: Always
status: {}
