apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment
    spec:
      containers:
      - image: payment-service:0.1
        name: payment
        ports:
        - containerPort: 8004
        resources: {}
        imagePullPolicy: Never
      restartPolicy: Always
status: {}
