apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-distribution-service
  name: payment-distribution-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-distribution-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-distribution-service
    spec:
      containers:
      - image: payment-distribution:0.1
        name: payment-distribution
        ports:
        - containerPort: 8003
        resources: {}
        imagePullPolicy: Never
      restartPolicy: Always
status: {}
