kind: PersistentVolume  
apiVersion: v1
metadata:
  name: mongodump-volume
  labels:
    type: local
    app: mongo-dump
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/minikube/data/mongodump"
    type: DirectoryOrCreate