kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodump-pv-claim
  labels:
    app: mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi