server:
  port: 8004
spring:
  application:
    name: payment-service
  cloud:
    stream:
      bindings:
        input: payments
  data:
   # mongodb:
    #  host: mongodb
  rabbitmq:
    host: localhost
    port: 5672
